# Generated by Django 5.0.7 on 2024-07-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by', models.CharField(max_length=255)),
                ('comments', models.IntegerField()),
                ('posted_at', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='media/RecntArticles')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
    ]
